//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFCKit2004.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_NEWSURFACEDLG               103
#define IDR_MAINFRAME                   128
#define IDR_MFCKITTYPE                  129
#define IDR_POPUPMENU                   131
#define ID_OPTIONS_FUZZINESS            134
#define ID_FUZZINESS_MORE               135
#define ID_FUZZINESS_LESS               136
#define ID_OPTIONS_RESET                137
#define ID_OPTIONS_MOUSESENSITIVITY     138
#define ID_MOUSESENSITIVITY_MORE        139
#define ID_MOUSESENSITIVITY_LESS        140
#define ID_MOUSESENSITIVITY_ROTATION    141
#define ID_MOUSESENSITIVITY_TRANSLATION 142
#define ID_MOUSESENSITIVITY_SCALING     143
#define ID_ROTATION_MORE                144
#define ID_ROTATION_LESS                145
#define ID_TRANSLATION_MORE             146
#define ID_TRANSLATION_LESS             147
#define ID_SCALING_MORE                 148
#define ID_SCALING_LESS                 149
#define ID_FRENET_SHOWAXES              150
#define ID_FRENET_SHOWFRENETFRAME       151
#define ID_FRENET_SHOWCURVATURE         152
#define ID_FRENET_SHOWTORSION           153
#define ID_FRENET_SHOW                  154
#define ID_FRENET_DRAWEVOLUTE           155
#define ID_FRENET_DRAWOFFSET            156
#define ID_FRENET_ANIMATION             157
#define ID_ANIMATION_START              158
#define ID_ANIMATION_STOP               159
#define ID_FRENET_PROPERTIES            160
#define IDD_DIALOG1                     161
#define IDR_MENU1                       163
#define IDR_MENU2                       164
#define IDR_MENU3                       166
#define IDR_MENU4                       167
#define IDD_SURF_GLOBALS                168
#define IDC_X_T                         1007
#define IDC_X_DEGREE                    1007
#define IDC_EDIT2                       1008
#define IDC_Z_T                         1008
#define IDC_SURFDLG_KVTXTV              1008
#define IDC_Y_T                         1009
#define IDC_X_SAMPLING_STEP             1009
#define IDC_SURFDLG_KVTXTU              1009
#define IDC_MIN_T                       1010
#define IDC_MAX_T                       1011
#define IDC_SURFDLG_CTRLPTS_U           1011
#define IDC_T_STEP                      1012
#define IDC_SURFDLG_CTRLPTS_V           1012
#define IDC_OFFSET_D                    1013
#define IDC_SURFDLG_ORDER_U             1013
#define IDC_OFFSET_D2                   1014
#define IDC_ANIM_SPEED                  1014
#define IDC_SURFDLG_ORDER_V             1014
#define IDC_SURFDLG_IMPORT_KNOTS        1015
#define IDC_SURFDLG_IMPORT_SURFACE2     1016
#define IDC_SURF_GLOBALS_ORDER_U        1016
#define IDC_SURF_GLOBALS_ORDER_V        1017
#define IDC_SURF_GLOBALS_SAMPLES_U      1018
#define IDC_SURF_GLOBALS_SAMPLES_V      1019
#define IDC_SURF_GLOBALS_ISOS_U         1020
#define IDC_SURF_GLOBALS_ISOS_U2        1021
#define IDC_SURF_GLOBALS_ISOS_V         1021
#define IDC_GLOBALS_KNOTSU              1022
#define IDC_GLOBALS_KNOTSV              1023
#define ID_POPUP_CLOSE                  32776
#define ID_STUFF_2                      32777
#define ID_STUFF_3                      32778
#define ID_STUFF_4                      32779
#define ID_STUFF_5                      32780
#define ID_FRENET_SHOW_OSC_SPHERE       32789
#define ID_STUFF_NEWBEZIERCURVE         32790
#define ID_STUFF_CLEARALL               32791
#define ID_CONTEXTBG_NEWBEZIERCURVE     32792
#define ID_CONTEXTBG_CLEARALL           32793
#define ID_Menu                         32794
#define ID_CONTEXTPOLYGON_INSERTPOINT   32795
#define ID_CONTEXTPOLYGON_APPENDPOINT   32796
#define ID_CONTEXTPOLYGON_SHOW          32797
#define ID_CONTEXTBG_NEWBSPLINECURVE    32798
#define ID_CONTEXTPT_ADJUSTWEIGHT       32799
#define ID_CONTEXTPOLYGON_RAISEDEGREE   32800
#define ID_CONTEXTPOLYGON_SUBDIVIDEATT  32801
#define ID_FILE_SAVEAS                  32802
#define ID_FILE_SAVEAS32803             32803
#define ID_CONTEXTPT_REMOVEPOINT        32804
#define ID_OPTIONS_SHOWGRID             32805
#define ID_FILE_SAVE32806               32806
#define ID_FILE_SAVE_GEOMETRY           32807
#define ID_FILE_SAVE32808               32808
#define ID_INSERTPOINT_APPENDPOINT      32809
#define ID_CONTEXTBSPLINEPOLY_INSERTPOINT 32810
#define ID_CONTEXTBSPLINEPOLY_MODIFYKNOTVECTOR 32811
#define ID_CONTEXTPOLYGON_CONNECTTOWITHCONTINUITY 32812
#define ID_CONNECTTOWITHCONTINUITY_G0   32813
#define ID_CONNECTTOWITHCONTINUITY_C1   32814
#define ID_CONNECTTOWITHCONTINUITY_G1   32815
#define ID_KNOTGUI_REMOVEKNOT           32816
#define ID_KNOTGUI_INSERTKNOT           32817
#define ID_CONTEXTBSPLINEPOLY_APPENDPOINT 32818
#define ID_KNOTGUI_REMOVEKNOT32819      32819
#define ID_KNOTGUI_INSERTKNOT32820      32820
#define ID_SURFACES_MODIFYKNOTVECTOR    32821
#define ID_MODIFYKNOTVECTOR_U           32822
#define ID_MODIFYKNOTVECTOR_V           32823
#define ID_CONTEXTBG_NEWSURFACE         32824
#define ID_SURFACES_GLOBALS             32825
#define ID_SURFACES_STARTANIMATION      32826
#define ID_SURFACES_STOPANIMATION       32827
#define ID_INDICATOR_CURVATURE          61205
#define ID_INDICATOR_TORSION            61206

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32828
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
